"""
AutoPenTest workspace cleanup helper.

Default cleanup removes transient runtime files that are regenerated by scans
or tests:
- storage/logs/
- storage/scans/
- storage/reports/
- Python __pycache__/ and *.pyc files

It does not delete saved result JSON or the local CVE mirror by default.
Use --include-results or --include-cve-data only when you intentionally want a
fresh demo workspace or a full CVE resync.
"""

from __future__ import annotations

import argparse
import os
import shutil
from pathlib import Path


def _display(path: Path, base_dir: Path) -> str:
    try:
        return str(path.relative_to(base_dir))
    except ValueError:
        return str(path)


def delete_file(path: Path, base_dir: Path, dry_run: bool = False) -> bool:
    """Delete one file if it exists."""
    if not path.exists():
        return False
    try:
        if dry_run:
            print(f"  Would delete: {_display(path, base_dir)}")
        else:
            path.unlink()
            print(f"  Deleted: {_display(path, base_dir)}")
        return True
    except OSError as exc:
        print(f"  Could not delete {_display(path, base_dir)}: {exc}")
        return False


def clear_directory(path: Path, base_dir: Path, dry_run: bool = False, recreate: bool = True) -> int:
    """Delete all children in a directory while preserving the directory."""
    if not path.exists():
        if recreate and not dry_run:
            path.mkdir(parents=True, exist_ok=True)
        print(f"  Skipped missing directory: {_display(path, base_dir)}")
        return 0

    deleted = 0
    for child in sorted(path.iterdir()):
        try:
            if dry_run:
                print(f"  Would delete: {_display(child, base_dir)}")
            elif child.is_dir() and not child.is_symlink():
                shutil.rmtree(child)
                print(f"  Deleted directory: {_display(child, base_dir)}")
            else:
                child.unlink()
                print(f"  Deleted: {_display(child, base_dir)}")
            deleted += 1
        except OSError as exc:
            print(f"  Could not delete {_display(child, base_dir)}: {exc}")

    if deleted == 0:
        print(f"  Already empty: {_display(path, base_dir)}")
    elif dry_run:
        print(f"  Would clear {deleted} item(s) from {_display(path, base_dir)}")
    else:
        print(f"  Cleared {deleted} item(s) from {_display(path, base_dir)}")

    if recreate and not dry_run:
        path.mkdir(parents=True, exist_ok=True)
    return deleted


def delete_pycache_directories(root_dir: Path, dry_run: bool = False) -> int:
    """Recursively delete Python __pycache__ directories."""
    deleted = 0
    for root, dirs, _files in os.walk(root_dir):
        if "__pycache__" not in dirs:
            continue
        pycache = Path(root) / "__pycache__"
        try:
            if dry_run:
                print(f"  Would delete: {_display(pycache, root_dir)}")
            else:
                shutil.rmtree(pycache)
                print(f"  Deleted directory: {_display(pycache, root_dir)}")
            deleted += 1
        except OSError as exc:
            print(f"  Could not delete {_display(pycache, root_dir)}: {exc}")

    if deleted == 0:
        print("  No __pycache__ directories found")
    return deleted


def delete_pyc_files(root_dir: Path, dry_run: bool = False) -> int:
    """Recursively delete compiled Python .pyc files."""
    deleted = 0
    for pyc_file in root_dir.rglob("*.pyc"):
        deleted += 1 if delete_file(pyc_file, root_dir, dry_run=dry_run) else 0

    if deleted == 0:
        print("  No .pyc files found")
    return deleted


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Clean generated AutoPenTest runtime files and Python caches.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show what would be deleted without deleting anything.",
    )
    parser.add_argument(
        "--include-results",
        action="store_true",
        help="Also clear storage/results/ saved scan dashboards and handoff JSON.",
    )
    parser.add_argument(
        "--include-cve-data",
        action="store_true",
        help="Also clear storage/mitre_cve/ so the CVE mirror/index must be synced again.",
    )
    parser.add_argument(
        "--keep-scan-evidence",
        action="store_true",
        help="Keep storage/scans/ command evidence files.",
    )
    return parser


def main() -> None:
    args = build_parser().parse_args()
    base_dir = Path(__file__).resolve().parents[1]
    storage_dir = base_dir / "storage"

    print("=" * 60)
    print("AUTOPENTEST CLEANUP")
    print("=" * 60)
    if args.dry_run:
        print("Dry run only. No files will be deleted.")

    cleanup_dirs = [
        storage_dir / "logs",
        storage_dir / "reports",
    ]

    if not args.keep_scan_evidence:
        cleanup_dirs.append(storage_dir / "scans")

    if args.include_results:
        cleanup_dirs.append(storage_dir / "results")

    if args.include_cve_data:
        cleanup_dirs.append(storage_dir / "mitre_cve")

    print("\nRuntime directories:")
    for directory in cleanup_dirs:
        clear_directory(directory, base_dir, dry_run=args.dry_run)

    print("\nPython caches:")
    delete_pycache_directories(base_dir, dry_run=args.dry_run)
    delete_pyc_files(base_dir, dry_run=args.dry_run)

    print("\nPreserved by default:")
    if not args.include_results:
        print("  storage/results/ saved scan JSON and handoff packages")
    if not args.include_cve_data:
        print("  storage/mitre_cve/ local official CVE mirror and index")
    print("  project/.env local configuration")

    print("\n" + "=" * 60)
    print("CLEANUP COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
