<?php
declare(strict_types=1);

/*
 * AutoPenTest lab diagnostics target.
 *
 * This page deliberately exposes only a narrow, non-destructive validation
 * behaviour expected by project/exploitation/web_validator.py. It does not
 * pass user input to a shell and therefore must not be used as a real command
 * execution or reverse-shell endpoint.
 */

const PAGE_TITLE = 'AutoPentest Lab Diagnostics';

function client_is_private_lab(): bool
{
    $ip = $_SERVER['REMOTE_ADDR'] ?? '';
    if (!filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
        return false;
    }

    $long = ip2long($ip);
    if ($long === false) {
        return false;
    }

    $ranges = [
        ['10.0.0.0', '10.255.255.255'],
        ['172.16.0.0', '172.31.255.255'],
        ['192.168.0.0', '192.168.255.255'],
        ['127.0.0.0', '127.255.255.255'],
    ];

    foreach ($ranges as [$start, $end]) {
        if ($long >= ip2long($start) && $long <= ip2long($end)) {
            return true;
        }
    }
    return false;
}

function validation_result(string $value): ?string
{
    /* Match the exact Linux arithmetic probe generated by web_validator.py:
       127.0.0.1; printf '%s\n' $((LEFT+RIGHT))
       The arithmetic is performed in PHP; no operating-system command runs. */
    $pattern = "/^127\\.0\\.0\\.1;\\s*printf\\s+'%s\\\\n'\\s+\\$\\(\\((\\d{1,6})\\+(\\d{1,6})\\)\\)\\s*$/";
    if (preg_match($pattern, trim($value), $matches) === 1) {
        return (string) ((int) $matches[1] + (int) $matches[2]);
    }

    if (filter_var(trim($value), FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
        return 'Target accepted: ' . trim($value);
    }

    return null;
}

$result = null;
$error = null;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!client_is_private_lab()) {
        http_response_code(403);
        $error = 'Requests are restricted to private lab networks.';
    } else {
        $host = (string) ($_POST['host'] ?? '');
        $result = validation_result($host);
        if ($result === null) {
            http_response_code(400);
            $error = 'Only an IPv4 address or the validator arithmetic probe is accepted.';
        }
    }
}
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?= htmlspecialchars(PAGE_TITLE, ENT_QUOTES, 'UTF-8') ?></title>
    <style>
        body { font-family: system-ui, sans-serif; max-width: 760px; margin: 3rem auto; padding: 0 1rem; line-height: 1.5; }
        form { display: flex; gap: .6rem; margin: 1.5rem 0; }
        input { flex: 1; padding: .7rem; }
        button { padding: .7rem 1rem; cursor: pointer; }
        pre { padding: 1rem; background: #f3f4f6; overflow-wrap: anywhere; }
        .error { color: #a40000; }
        .notice { color: #555; }
    </style>
</head>
<body>
    <h1><?= htmlspecialchars(PAGE_TITLE, ENT_QUOTES, 'UTF-8') ?></h1>
    <p class="notice">Authorised private-lab validation endpoint.</p>

    <form action="/diagnostics.php" method="POST">
        <label for="host">Host</label>
        <input id="host" name="host" type="text" value="127.0.0.1" required>
        <button type="submit">Run diagnostic</button>
    </form>

    <?php if ($result !== null): ?>
        <pre><?= htmlspecialchars($result, ENT_QUOTES, 'UTF-8') ?></pre>
    <?php endif; ?>

    <?php if ($error !== null): ?>
        <p class="error"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></p>
    <?php endif; ?>
</body>
</html>
